# Generated by Django 3.1.4 on 2020-12-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
