# Generated by Django 3.1.4 on 2020-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='quantityPlaces',
            field=models.IntegerField(default=2),
        ),
    ]
