# Generated by Django 3.1.4 on 2020-12-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_table_quantityplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numberTable',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='quantityPlaces',
            field=models.IntegerField(default=1),
        ),
    ]
