# Generated by Django 3.1.4 on 2020-12-08 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 12, 8, 17, 8, 32, 881948, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
