# Generated by Django 3.1.4 on 2020-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_auto_20201208_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.TimeField(),
        ),
    ]
