# Generated by Django 3.1.4 on 2020-12-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_auto_20201208_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('weight', models.IntegerField(default=50)),
                ('price', models.IntegerField(default=50)),
            ],
        ),
    ]
