# Generated by Django 3.1.4 on 2020-12-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0011_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
