# Generated by Django 3.1.4 on 2020-12-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=400)),
                ('dish', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reserve.dish')),
            ],
        ),
    ]
