# Generated by Django 3.1.4 on 2020-12-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0015_auto_20201215_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('patronymic', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('vacancy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reserve.jobvacancy')),
            ],
        ),
    ]
