# Generated by Django 3.1.4 on 2020-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0017_order_dishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishList',
            field=models.ManyToManyField(null=True, to='reserve.Dish', verbose_name='dishList'),
        ),
    ]
