# Generated by Django 3.1.4 on 2020-12-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_auto_20201220_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantityArray',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
