# Generated by Django 3.1.4 on 2020-12-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0021_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('responsible', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reserve.responsible')),
            ],
        ),
    ]
